// <auto-generated />
using System;
using CRV.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRV.Core.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260905025159_StoreDecimalsAsReal")]
    partial class StoreDecimalsAsReal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CRV.Core.Data.BacktestRunRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<double>("NetPnl")
                        .HasColumnType("REAL");

                    b.Property<double>("ProfitFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("CRV.Core.Models.GroupOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccruedPartialPnl")
                        .HasColumnType("REAL");

                    b.Property<bool>("AutoTrailActivated")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AutoTrailFreq")
                        .HasColumnType("REAL");

                    b.Property<double?>("AutoTrailHighWater")
                        .HasColumnType("REAL");

                    b.Property<double?>("AutoTrailStopLoss")
                        .HasColumnType("REAL");

                    b.Property<double?>("AutoTrailTrigger")
                        .HasColumnType("REAL");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerStrategyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("GroupOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InitialStopPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("PartialContracts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingStopIdsCsv")
                        .HasColumnType("TEXT");

                    b.Property<double>("PointValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stop2OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalContracts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GroupOrderId")
                        .IsUnique();

                    b.HasIndex("SetupId");

                    b.ToTable("GroupOrders");
                });

            modelBuilder.Entity("CRV.Core.Models.OptionChainSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AtmImpliedVol")
                        .HasColumnType("REAL");

                    b.Property<double>("AtmStrike")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysToExpiration")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ExpectedMove")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UnderlyingPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TradeDate");

                    b.HasIndex("Underlying", "Expiration", "TradeDate")
                        .IsUnique();

                    b.ToTable("OptionChainSnapshots");
                });

            modelBuilder.Entity("CRV.Core.Models.OptionOrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breakevens")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FilledNetPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketAtSubmitJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxLoss")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxProfit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MidNetPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("NetPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Spreads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalNet")
                        .HasColumnType("REAL");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlacedAt");

                    b.HasIndex("Underlying");

                    b.ToTable("OptionOrders");
                });

            modelBuilder.Entity("CRV.Core.Models.OrderLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FillPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("FillTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderLegs");
                });

            modelBuilder.Entity("CRV.Core.Models.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FillPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LimitPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("OcoGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("StopPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Broker");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlacedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CRV.Core.Models.StrategyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowBothSameBar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AtrFilterPct")
                        .HasColumnType("REAL");

                    b.Property<bool>("AutoSizeByRiskA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSizeByRiskB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSizeByRiskC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSizeByRiskD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasketJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChopBlockMode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChopCompressionRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("ChopFlatSlopeThresholdPct")
                        .HasColumnType("REAL");

                    b.Property<double>("ChopMinDriveRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("ChopMinVolumeRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("ChopMinVotes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChopUseFlatVwap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChopUseLowVolume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChopUseRangeCompression")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChopUseWeakDrive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CommissionPerSide")
                        .HasColumnType("REAL");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyLossMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriveBullBearRatio")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DriveMaxPullback")
                        .HasColumnType("REAL");

                    b.Property<double>("DriveRangeAtrMult")
                        .HasColumnType("REAL");

                    b.Property<string>("Ema21BasketJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailBatchIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailOnDailyLossBreached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnDailyLossBreachedMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnEngineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnEngineStatusMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnEntryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnExit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnExitMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnOrbFormed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnOrbFormedMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnSessionChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailOnSessionChangeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnSessionEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailRecipients")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecBroker")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionTFMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FBMaxPenetrationPctOrb")
                        .HasColumnType("REAL");

                    b.Property<double>("FBMaxPenetrationPctSR")
                        .HasColumnType("REAL");

                    b.Property<int>("FBMaxTimeOutsideMinutesOrb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FBMaxTimeOutsideMinutesSR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FBMaxTrendDayScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FBMinRejectionBodyPct")
                        .HasColumnType("REAL");

                    b.Property<double>("HiVolMult")
                        .HasColumnType("REAL");

                    b.Property<double>("HiVolMultA")
                        .HasColumnType("REAL");

                    b.Property<double>("HiVolMultB")
                        .HasColumnType("REAL");

                    b.Property<double>("HiVolMultC")
                        .HasColumnType("REAL");

                    b.Property<double>("HiVolMultD")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxContracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDailyLoss")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxLongTradesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLongTradesB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxShortTradesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxShortTradesB")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxTradeRiskA")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxTradeRiskB")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxTradeRiskC")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxTradeRiskD")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxTradesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinRrA")
                        .HasColumnType("REAL");

                    b.Property<double>("MinRrB")
                        .HasColumnType("REAL");

                    b.Property<double>("MinRrC")
                        .HasColumnType("REAL");

                    b.Property<double>("MinRrD")
                        .HasColumnType("REAL");

                    b.Property<string>("ModeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NearPct")
                        .HasColumnType("REAL");

                    b.Property<double>("NearPctA")
                        .HasColumnType("REAL");

                    b.Property<double>("NearPctB")
                        .HasColumnType("REAL");

                    b.Property<double>("NearPctC")
                        .HasColumnType("REAL");

                    b.Property<double>("NearPctD")
                        .HasColumnType("REAL");

                    b.Property<TimeOnly>("OrbEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OrbStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartialCtsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PointValue")
                        .HasColumnType("REAL");

                    b.Property<double>("PointValueA")
                        .HasColumnType("REAL");

                    b.Property<double>("PointValueB")
                        .HasColumnType("REAL");

                    b.Property<double>("PointValueC")
                        .HasColumnType("REAL");

                    b.Property<double>("PointValueD")
                        .HasColumnType("REAL");

                    b.Property<double>("PullbackPct")
                        .HasColumnType("REAL");

                    b.Property<int>("ReplayBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReplayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplaySpeed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RetestPct")
                        .HasColumnType("REAL");

                    b.Property<TimeOnly>("RthEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RthStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveReplayTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ShallowPullbackMax")
                        .HasColumnType("REAL");

                    b.Property<string>("StopModeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopModeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopModeC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopModeD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StopPctA")
                        .HasColumnType("REAL");

                    b.Property<double>("StopPctB")
                        .HasColumnType("REAL");

                    b.Property<double>("StopPctC")
                        .HasColumnType("REAL");

                    b.Property<double>("StopPctD")
                        .HasColumnType("REAL");

                    b.Property<int>("StopVwapTicksA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopVwapTicksB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopVwapTicksC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopVwapTicksD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SweepConfirmBars")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SweepEqualTolerance")
                        .HasColumnType("REAL");

                    b.Property<double>("SweepMinBodyReject")
                        .HasColumnType("REAL");

                    b.Property<double>("SweepMinPenetration")
                        .HasColumnType("REAL");

                    b.Property<int>("TargetPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctD")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TickSize")
                        .HasColumnType("REAL");

                    b.Property<double>("TickSizeA")
                        .HasColumnType("REAL");

                    b.Property<double>("TickSizeB")
                        .HasColumnType("REAL");

                    b.Property<double>("TickSizeC")
                        .HasColumnType("REAL");

                    b.Property<double>("TickSizeD")
                        .HasColumnType("REAL");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrendDayThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseChopFilter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCloseConfirmationA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseDailyLossLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTimeFilter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VwapDevPeriod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("CRV.Core.Models.StrategyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerStrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialContracts")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PointValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalContracts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrokerStrategyId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("StrategyLogs");
                });

            modelBuilder.Entity("CRV.Core.Models.TradeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Commission")
                        .HasColumnType("REAL");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Entry")
                        .HasColumnType("REAL");

                    b.Property<double>("Exit")
                        .HasColumnType("REAL");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("GrossPnl")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialStop")
                        .HasColumnType("REAL");

                    b.Property<double>("NetPnl")
                        .HasColumnType("REAL");

                    b.Property<double>("Partial")
                        .HasColumnType("REAL");

                    b.Property<bool>("PartialFilled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PartialPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("RMultiple")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Target")
                        .HasColumnType("REAL");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnteredAt");

                    b.HasIndex("ExitReason");

                    b.HasIndex("SessionId");

                    b.HasIndex("Source");

                    b.HasIndex("Ticker");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
