// <auto-generated />
using System;
using CRV.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRV.Core.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260325205124_AddGroupOrders")]
    partial class AddGroupOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CRV.Core.Data.BacktestRunRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("CRV.Core.Models.GroupOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccruedPartialPnl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartialContracts")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalContracts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GroupOrderId")
                        .IsUnique();

                    b.HasIndex("SetupId");

                    b.ToTable("GroupOrders");
                });

            modelBuilder.Entity("CRV.Core.Models.OrderLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FillTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderLegs");
                });

            modelBuilder.Entity("CRV.Core.Models.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OcoGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Broker");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlacedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CRV.Core.Models.StrategyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowBothSameBar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRearmAfterBeD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AtrFilterPct")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasketJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CloseAtRthClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionPerSide")
                        .HasColumnType("TEXT");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriveBullBearRatio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DriveMaxPullback")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DriveRangeAtrMult")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecBroker")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionTFMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FBMaxPenetrationPctOrb")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FBMaxPenetrationPctSR")
                        .HasColumnType("TEXT");

                    b.Property<int>("FBMaxTimeOutsideMinutesOrb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FBMaxTimeOutsideMinutesSR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FBMaxTrendDayScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FBMinRejectionBodyPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMult")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultD")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAdverseMinutesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAdverseMinutesB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAdverseMinutesC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAdverseMinutesD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTradesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinRrA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRrB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRrC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRrD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPctA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPctB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPctC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPctD")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OrbEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OrbStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTypeD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartialCtsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialCtsD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointValueA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointValueB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointValueC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointValueD")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PullbackPct")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReplayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplaySpeed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RetestPct")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RthEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RthStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaveReplayTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShallowPullbackMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPctA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPctB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPctC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPctD")
                        .HasColumnType("TEXT");

                    b.Property<int>("SweepConfirmBars")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SweepEqualTolerance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SweepMinBodyReject")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SweepMinPenetration")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctD")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSizeA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSizeB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSizeC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSizeD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrendDayThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCustomTickerD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseDailyLossLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTimeFilter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VwapDevPeriod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("CRV.Core.Models.TradeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Entry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Exit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Partial")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PartialFilled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PartialPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RMultiple")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnteredAt");

                    b.HasIndex("ExitReason");

                    b.HasIndex("SessionId");

                    b.HasIndex("Source");

                    b.HasIndex("Ticker");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
