// <auto-generated />
using System;
using CRV.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRV.Core.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260312214512_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CRV.Core.Data.BacktestRunRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("CRV.Core.Models.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OcoGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Broker");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlacedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CRV.Core.Models.StrategyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowBothSameBar")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AtrFilterPct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CloseAtRthClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAtRthCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionPerSide")
                        .HasColumnType("TEXT");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffHourB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffMinuteB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryTickOffsetB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecBroker")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionTFMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HiVolMult")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HiVolMultB")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxContracts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContractsB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTradesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTradesB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinRrA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRrB")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NearPct")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OrbEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OrbStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartialPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialPctB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PullbackPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetestPct")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RthEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("RthStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopPctA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPctB")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPctA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPctB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBeB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseDailyLossLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbClose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseOrbCloseB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsePartialB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTimeFilter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseVwapB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("CRV.Core.Models.TradeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<int>("Contracts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Entry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Exit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Partial")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PartialFilled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PartialPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RMultiple")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnteredAt");

                    b.HasIndex("ExitReason");

                    b.HasIndex("SessionId");

                    b.HasIndex("Source");

                    b.HasIndex("Ticker");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
